
# NOTA: Este fichero NO se recarga automaticamente cuando se usa `rake serve`

# Variables globales de configuracion
name: El Concilio
title: El Concilio
email: aeelconcilio.asociacion.ciencias@uam.es
description: >
  Somos la asociación estudiantil Club de Rol El Concilio,
  de la Universidad Autónoma de Madrid, y si has llegado hasta aquí,
  ¡es porque tienes interés en la asociación!

baseurl: "" # subpath
url: "" # hostname & protocol
lang: es

# Configuracion de compilacion
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-coffeescript
exclude:
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - Rakefile

# Configuracion de las paginas
defaults:
  -
    scope:
      path: "" # todos los ficheros del proyecto
    values:
      layout: "default"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

collections:
  posts:
    permalink: /blog/:year/:month/:day/:title/

# Configuracion propia
nav-bar:
  - 
    text: Novedades
    url: /blog/
  - 
    text: Índice
    url: /archivo/
  - 
    text: Inventario
    url: /juegos/mesa/
  - 
    text: Calendario
    url: /calendario/
  - 
    text: FAQ
    url: /faq/
  - 
    text: Sobre nosotros
    url: /sobrenosotros/

scripts:
  - /assets/scripts/external-links.js
  - /assets/scripts/game-table.js
  - /assets/scripts/easter-egg.js

stylesheets:
  - /assets/styles/main.css
  - /assets/styles/extra.css
  - //maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
