
# NOTA: Este fichero NO se recarga automaticamente cuando se usa `rake serve`

# Variables globales de configuracion
name: El Concilio
title: El Concilio
email: aeelconcilio.asociacion.ciencias@uam.es
description: >
  Somos la asociación estudiantil Club de Rol El Concilio,
  de la Universidad Autónoma de Madrid, y si has llegado hasta aquí,
  ¡es porque tienes interés en la asociación!

baseurl: "" # subpath
url: "" # hostname & protocol
lang: es

# Configuracion de compilacion
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-coffeescript
exclude:
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - Rakefile

# Configuracion de las paginas
defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "news"

collections:
  posts:
    permalink: /noticias/:year/:month/:day/:title/

# Configuracion propia
nav-bar:
  Noticias: /noticias/
  Eventos: /noticias/eventos/
  Inventario: /juegos/mesa/
  Encuéntranos: /encuentranos/

scripts:
  - /assets/js/external-links.js
  - /assets/js/game-table.js

stylesheets:
  - /assets/css/main.css
  - /assets/css/extra.css
  - //maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
